debug: true

file.dir: /Users/doublejkim/filestore_temp/   # NAS 같은 스토리지 위치 지정. 마지막 slash 까지 작성하고 활용하는게 좋음

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minitable
    driver-class-name: org.mariadb.jdbc.Driver
    username: dbuser
    password: dbuser123
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  # Querydsl 사용할경우 jpql 을 확인하고싶을경우 주석으로 볼수있음
    show-sql: true
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username:  # SMTP 서버 로그인 아이디 (발신자)
    password:  # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 7MB


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace # spring jpa 단위에서 파라미터 확인
  example.minitable: debug
  #org.hibernate.type: trace



server:
  error:
    whitelabel:
      enabled: false